dist: trusty
sudo: false

matrix:
  include:
    # ========================================================================
    - os: linux
      language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
            - libboost-test-dev
      env: TARGET=cpp_stl
    - os: linux
      language: cpp
      compiler: clang
      addons:
        apt:
          packages:
            - libboost-test-dev
      env: TARGET=cpp_stl
    - os: osx
      language: cpp
      compiler: clang
      addons:
        apt:
          packages:
            - libboost-test-dev
      env: TARGET=cpp_stl
    # ========================================================================
    # Disabled: our runtime now uses java.nio extensively => JDK7+ only
#   - os: linux
#     sudo: true
#     language: java
#     jdk: openjdk6
#     env: TARGET=java
    - os: linux
      sudo: true
      language: java
      jdk: oraclejdk7
      env: TARGET=java
    - os: linux
      sudo: true
      language: java
      addons:
        apt:
          packages:
            - oracle-java8-installer
      jdk: oraclejdk8
      env: TARGET=java
    # ========================================================================
    - os: linux
      language: ruby
      rvm: 1.8.7
      env: TARGET=ruby
    - os: linux
      language: ruby
      rvm: 1.9.3
      env: TARGET=ruby
    - os: linux
      rvm: 2.3.1
      language: ruby
      env: TARGET=ruby
    # ========================================================================
    - os: linux
      language: python
      python: 2.7
      env: TARGET=python
    - os: linux
      language: python
      python: 3.6
      env: TARGET=python

install:
  - git clone https://github.com/kaitai-io/kaitai_struct_tests tests
  - ln -s ../compiled tests/compiled
  - ./prepare-$TARGET
  - cd tests

script:
  - ./run-$TARGET

deploy:
  provider: bintray
  file: ../bintray.json
  user: greycat
  key:
    secure: Gf6j89xDxdfd9YczrJ4f5Rg8CZTBqIJiB5YrXLd0KOPkLNKzYqS3kO57o3CX1VGbMupJzcjubE4o+GnnXSK2v50KnGLzI0A2Mp3nsP/X/tZmCS3AD6JQjsqC/Z7QN7tZd8QKMyeUdb/S40Oc9lYvHzJYPPQwiAc9EXu1wMfKoTro8feA9tPH0/vSKJztW+KYkMzKyN/gx5X3CXZEMmJhXBtHS5YeZDFxlYCaVE/+aA8q8zzmQ1dQnJpC9mLO0yUPaGVHbrUgOWaC2mmqw9wh8n5kmVEBSByFn382eWApxmPDJB/DMDGEVtQvS2+uCOAKtFO+fPE4wcv1TXsjBTVKc1S3aPZnfD7MBtrfBx+UKht9NL/4M685KZZ934La/VIPsVaS5rezv+BxJBt//trRJDixH4WLADnpB3fCmAodT1WTguiGimFdBHHAxyqInXTy/vVq2QTaH0SlXrt9jL2zwKnJzMaJAgfxOEMi3jfj+9OYIsCSFjtKAVAvtEIAv0Mk1LspcugQDt+0x9Qu31j6yfOSraGZZJ2emYSiInA5XKWq8LbuuaYflqDZfhzosS+b0MP1+Upgz+GOxfiINaS7HX77J3Vfvxt1cfriP+QCNfLaSePl/mC5HfXdBIRoJ/mLXWuTy4te/Wo0hOIqm4x84MSVa6d9t3T84PCqa/aZnIM=
