dist: trusty
sudo: false

matrix:
  include:
    # ========================================================================
    - os: linux
      sudo: true
      language: java
      jdk: openjdk6
      env: TARGET=java
    - os: linux
      sudo: true
      language: java
      jdk: oraclejdk7
      env: TARGET=java
    - os: linux
      sudo: true
      language: java
      addons:
        apt:
          packages:
            - oracle-java8-installer
      jdk: oraclejdk8
      env: TARGET=java
    # ========================================================================
    - os: linux
      language: ruby
      rvm: 1.8.7
      env: TARGET=ruby
    - os: linux
      language: ruby
      rvm: 1.9.3
      env: TARGET=ruby
    - os: linux
      rvm: 2.3.1
      language: ruby
      env: TARGET=ruby
    # ========================================================================
    - os: linux
      language: python
      python: 2.7
      env: TARGET=python
    - os: linux
      language: python
      python: 3.6
      env: TARGET=python

install:
  - git clone https://github.com/kaitai-io/kaitai_struct_tests tests
  - ln -s ../compiled tests/compiled
  - ./prepare-$TARGET
  - cd tests

script:
  - ./run-$TARGET
