name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet:
          - 2.2.103
          - 3.0.100
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{matrix.dotnet}}
      - name: prepare
        run: |
          git clone https://github.com/kaitai-io/kaitai_struct_tests tests
          ln -s ../compiled tests/compiled
          ./prepare-csharp
      - name: run
        run: |
          cd tests
          ./ci-csharp
          cd ..
