name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tsv:
          - target: csharp
            subtarget: ''
            variety: netcore2.2.103_linux
            dotnet: 2.2.103
          - target: csharp
            subtarget: ''
            variety: netcore3.0.100_linux
            dotnet: 3.0.100
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{matrix.tsv.dotnet}}
        if: matrix.tsv.dotnet
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - name: prepare
        run: |
          git clone https://github.com/kaitai-io/kaitai_struct_tests tests
          ln -s ../compiled tests/compiled
          ./prepare-${{matrix.tsv.target}}
      - name: run
        run: |
          cd tests
          ./ci-${{matrix.tsv.target}}
          cd ..
      - name: publish
        env:
          BOT_SSH_KEY: ${{secrets.BOT_SSH_KEY}}
        run: |
          ./publish
